# Generated by Django 6.0.2 on 2026-02-20 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10)),
                ('group_deadline', models.DateTimeField()),
                ('proposal_deadline', models.DateTimeField()),
                ('final_deadline', models.DateTimeField()),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseConfig',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.course'),
        ),
    ]
