# Generated by Django 6.0.2 on 2026-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_course_delete_courseconfig_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project_description',
            field=models.TextField(blank=True),
        ),
    ]
